[package]
name = "sandspiel_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy  = {version = "0.13", features =["file_watcher"]}
rand = "0.8.3"
rand_xoshiro = "0.6.0"
bytemuck = "1.21.0"

